# scalpel.conf
# -----------------------------------------------------------------------
# JPG
# -----------------------------------------------------------------------
jpg  y  20000000  \xff\xd8\xff\xe0  \xff\xd9
jpg  y  20000000  \xff\xd8\xff\xe1  \xff\xd9

# -----------------------------------------------------------------------
# PNG
# -----------------------------------------------------------------------
png  y  20000000  \x89\x50\x4e\x47\x0d\x0a\x1a\x0a  \x00\x00\x00\x00\x49\x45\x4e\x44\xae\x42\x60\x82

# -----------------------------------------------------------------------
# PDF
# -----------------------------------------------------------------------
pdf  y  20000000  %PDF-  %%EOF

# -----------------------------------------------------------------------
# ZIP
# -----------------------------------------------------------------------
zip  y  20000000  PK\x03\x04  PK\x05\x06
